### ISSUE TITLE
Streaming mode

### ISSUE THREAD

**Issue by mazorigal** [stefansavev/random-projections-at-berlinbuzzwords#1]
Hi,

Is there any option to update the search index from a continues data stream, instead of building the index in a batch mode ?

Thanks,

**Comment by stefansavev** [comment]
No, but this is because there is a better way.
It is better to use this method with an indexing engine like Elasticsearch or Solr, even though they may not support it it natively.

This is how:

0. Suppose you have a dataset of 1 million points.
1. Take a sample (e.g. 200000)
2. Index the sample with this tool or a similar one (see here)
3. Run your full dataset of 1 million points against the index and compute (e.g 100) nearest neighbors
4. Now you have a transformed dataset of the form: 
```
original_point_id: [neighbor1_id, neighbor2_id, ...]
```
Treat this dataset as documents for Elasticsearch. Index the transformed dataset.
5. Search with Elasticsearch. When you retrieve a result set at search time with Elasticsearch, you take, for example, 100 top results and you can rescore them exactly. In Elasticsearch you can also keep the dense vectors.

How do you use this approach in a streaming way:
This just point 4. When a new point comes in, you transform it and send to to Elasticsearch for indexing.
A the end of every day or every week you have have to redo all steps 1-4 and reindex if the distribution changes substantially. 

There are a few things to watch: 
- points from the sample that are exactly the same or very close. It will be better at preprocessing time to collapse them. 
- elasticsearch similarity (do you benefit from tf-idf or its better to use no weighting).

You can also research the newest methods for NN search from here: http://searchivarius.org/about.

If you are indexing images, you might be inspired by https://erikbern.com/2015/09/24/nearest-neighbor-methods-vector-models-part-1.html to use a convolutional neural network for similarity.

If you are using text, I suggest to use a mixed approach which also includes the tokenized and indexed raw text in addition to the "dense"/"dimensionality reduction" apporach. I believe there you can also benefit by embedding documents with a neural net but I don't have pointers.

There are two advantages to this approach:
- you can now search together with other criteria (e.g. some flags or date ranges)
- you can also delete and update
- for serving you will be using an established, well understood system. Your operations people will be happier with this approach instead of using an unknown system.

If you have had success with this approach please report back here.
